baseURL = "https://yaviewpoint.icu/"
languageCode = "zh-cn"
title = "Yet Another Viewpoint"
theme = "PaperMod"

[params]
  author = "XClear"
  description = "My personal blog"
  ShowReadingTime = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  hasCJKLanguage = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[params.DateFormat]
  list   = "2006-01-02"
  single = "2006-01-02 15:04"    # 文章页显示到分钟

[markup]
  [markup.highlight]
    style = "github"
    lineNos = true
